export const MOOD_META = {
  happy: {
    emoji: '😊',
    label: 'Happy',
    tagline: 'Excited & energetic',
    color: '#f59e0b',
    badgeBg: 'bg-amber-100',
    badgeText: 'text-amber-800',
    borderColor: 'border-amber-300',
  },
  sad: {
    emoji: '😔',
    label: 'Sad',
    tagline: 'Quiet & down',
    color: '#6366f1',
    badgeBg: 'bg-indigo-100',
    badgeText: 'text-indigo-800',
    borderColor: 'border-indigo-300',
  },
  angry: {
    emoji: '😤',
    label: 'Angry',
    tagline: 'Irritated & blunt',
    color: '#ef4444',
    badgeBg: 'bg-rose-100',
    badgeText: 'text-rose-800',
    borderColor: 'border-rose-300',
  },
  mother: {
    emoji: '🥰',
    label: 'Caring',
    tagline: 'Warm & protective',
    color: '#ec4899',
    badgeBg: 'bg-pink-100',
    badgeText: 'text-pink-800',
    borderColor: 'border-pink-300',
  },
  drama: {
    emoji: '🙄',
    label: 'Drama',
    tagline: 'Playfully offended',
    color: '#a855f7',
    badgeBg: 'bg-purple-100',
    badgeText: 'text-purple-800',
    borderColor: 'border-purple-300',
  },
  normal: {
    emoji: '🙂',
    label: 'Normal',
    tagline: 'Balanced everyday flow',
    color: '#64748b',
    badgeBg: 'bg-slate-200',
    badgeText: 'text-slate-800',
    borderColor: 'border-slate-300',
  },
  curious: {
    emoji: '🤔',
    label: 'Curious',
    tagline: 'Inquisitive & deep',
    color: '#0ea5e9',
    badgeBg: 'bg-sky-100',
    badgeText: 'text-sky-800',
    borderColor: 'border-sky-300',
  },
  tired: {
    emoji: '😴',
    label: 'Tired',
    tagline: 'Low battery & groggy',
    color: '#8b5cf6',
    badgeBg: 'bg-violet-100',
    badgeText: 'text-violet-800',
    borderColor: 'border-violet-300',
  },
};

export const REACTION_EMOJIS = {
  laugh: '😂',
  love: '❤️',
  sad: '😢',
  angry: '💢',
  eye_roll: '🙄',
  shock: '😱',
  thinking: '💡',
  sleepy: '💤',
  care: '🫂',
  dramatic: '🎭',
};

export const DEFAULT_SETTINGS = {
  characterName: 'Mira',
  soundEnabled: true,
  typingAnimationEnabled: true,
  reactionsEnabled: true,
  moodIndicatorEnabled: true,
  developerMode: false,
};
